version: 0.2
phases:
  pre_build:
    commands:
      - TAG="$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - echo "Update Image tag in kube-manifest..."
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI/$IMAGE_REPO_NAME:$TAG"'@' deployment.yml
      - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - echo "Login in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME $REPOSITORY_URI/$IMAGE_REPO_NAME:$TAG
      - docker push $REPOSITORY_URI/$IMAGE_REPO_NAME:$TAG
      - echo "Update Kube Config"
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl apply -f deployment.yml
      - echo "Completed applying changes to Kubernetes Objects"
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $REPOSITORY_URI/$IMAGE_REPO_NAME:$TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
